kanban_app/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from .database import db
from flask_login import login_user, login_required, logout_user, current_user

from .model import User

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=["GET", "POST"])
def register():
    if request.method == "POST":

        if User.query.filter_by(email=request.form.get('email')).first():
            #User already exists
            flash("You've already signed up with that email, log in instead!")
            return redirect(url_for('auth.login'))

        hash_and_salted_password = generate_password_hash(
            request.form.get('password'),
            method='pbkdf2:sha256',
            salt_length=8
        )

        new_user = User(
            email=request.form.get('email'),
            name=request.form.get('name'),
            password=hash_and_salted_password,
        )

        db.session.add(new_user)
        db.session.commit()

        login_user(new_user)
        return redirect(url_for('views.board'))

    return render_template("register.html", logged_in=current_user.is_authenticated)


@auth.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')
    
        user = User.query.filter_by(email=email).first()
        #Email doesn't exist or password incorrect.
        if not user:
            flash("That email does not exist, please try again.")
            return redirect(url_for('auth.login'))
        elif not check_password_hash(user.password, password):
            flash('Password incorrect, please try again.')
            return redirect(url_for('auth.login'))
        else:
            login_user(user)
            return redirect(url_for('views.board'))

    return render_template("login.html", logged_in=current_user.is_authenticated)




@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

kanban_app/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from .database import db
from .model import Todo_list, Card
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
 

views = Blueprint('views', __name__)


@views.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('views.board', user=current_user))
    return render_template("index.html", logged_in=current_user.is_authenticated)


@views.route('/board', methods=["GET", "POST"])
@login_required
def board():
    user_lists = current_user.lists
    user_cards = []
    for i in user_lists:
        user_cards.append(i.cards)
    return render_template("board.html", user=current_user, logged_in=current_user.is_authenticated, 
    user_lists=user_lists, user_cards=user_cards)


#######################################################

@views.route('/list/create', methods=['GET', 'POST'])
def createList():
    if request.method == "POST":
        title = request.form.get("name")
        description = request.form.get("description")

        new_list = Todo_list(
            list_name=title,
            description=description,
            user_id=current_user.id
        )

        db.session.add(new_list)
        db.session.commit()
        return redirect(url_for('views.board', user=current_user))
    return render_template("newList.html", user=current_user)


@views.route('/list/<int:id>/update', methods=['GET', 'POST'])
def updateList(id):
    if request.method == "POST":
        title = request.form.get("name")
        description = request.form.get("description")
        f = Todo_list.query.filter_by(list_id=id).first()
        f.list_name = title
        f.description = description

        db.session.commit()
        return redirect(url_for('views.board', user=current_user))

    z = Todo_list.query.filter_by(list_id=id).first()
    return render_template("editList.html", user=current_user, curr_id=id, curr_list=z)


@views.route('/list/<int:id>/delete', methods=['GET', 'POST'])
def deleteList(id):

    l = Todo_list.query.filter_by(list_id=id).first()
    db.session.delete(l)
    db.session.commit()
    return redirect(url_for('views.board', user=current_user))


############################################################

@views.route('/card/<int:li_id>/create', methods=['GET', 'POST'])
def createCard(li_id):
    if request.method == "POST":

        up_list_id = request.form.get('list-card')

        name = request.form.get('name')
        content = request.form.get('content')
        format = '%Y-%m-%d'
        e_date = request.form.get('deadline')
        new_date = datetime.strptime(e_date, format)

        percent = request.form.get('completed_percent')


        deadline = new_date
        t_date = datetime.today().strftime(format)

        last_updated_date = datetime.strptime(t_date, format)

        todo_list = Todo_list.query.filter_by(list_id=li_id).first()
        todo_list.tasks_remaining += 1
        if percent == '100':
            todo_list.tasks_completed += 1
            todo_list.tasks_remaining -= 1

        new_card = Card(
            card_title=name,
            content=content,
            deadline=deadline,
            li=up_list_id,
            is_complete=percent,
            task_updated_date=last_updated_date
        )

        db.session.add(new_card)
        db.session.commit()
        return redirect(url_for('views.board', user=current_user, t_date=t_date))

    t_date = datetime.today().strftime('%Y-%m-%d')
    return render_template("newCard.html", user=current_user, li_id=li_id, t_date=t_date)


@views.route('/card/<int:c_id>/update', methods=['GET', 'POST'])
def updateCard(c_id):
    if request.method == "POST":

        up_list_id = request.form.get('list-card')
        name = request.form.get('name')
        content = request.form.get('content')
        format = '%Y-%m-%d'
        e_date = request.form.get('deadline')
        new_date = datetime.strptime(e_date, format)
        deadline = new_date
        t_date = datetime.today().strftime('%Y-%m-%d')
        
        last_updated_date = datetime.strptime(t_date, format)
        percent = request.form.get('completed_percent')

        c1 = Card.query.filter_by(card_id=c_id).first()

        c1.deadline = deadline
        c1.content = content
        c1.is_complete = percent
        c1.li = up_list_id
        c1.card_title = name
        c1.task_updated_date = last_updated_date

        todo_list = Todo_list.query.filter_by(list_id=c1.li).first()        
        if percent == '100': 
            todo_list.tasks_completed += 1
            todo_list.tasks_remaining -= 1
        db.session.commit()

        return redirect(url_for('views.board', user=current_user, t_date=t_date))

    c = Card.query.filter_by(card_id=c_id).first()
    li_id = c.li
    t_date = datetime.today().strftime('%Y-%m-%d')
    return render_template("editCard.html", user=current_user, c_id=c_id, li_id=li_id, c=c, t_date=t_date)


@views.route('/card/<int:c_id>/delete', methods=['GET', 'POST'])
def deleteCard(c_id):
    l = Card.query.filter_by(card_id=c_id).first()
    
    todo_list = Todo_list.query.filter_by(list_id=l.li).first()        
    if l.is_complete == 100:
        todo_list.tasks_completed += 1
    else:
        todo_list.tasks_remaining -= 1

    db.session.delete(l)
    db.session.commit()

    return redirect(url_for('views.board'))


############################################################

@views.route('/board/summary', methods=["GET", "POST"])
@login_required
def summary():
    sns.set()
    user_lists = current_user.lists
    for i in user_lists:
        plt.clf()
        titles = []

        for j in range(len(i.cards)):
            b = None
            if i.cards[j].task_updated_date != None:
                b = i.cards[j].task_updated_date.strftime('%d-%m-%Y')
            if b != None:
                titles.append(i.cards[j].card_title + f"_{j+1}\n" + b)
            else:
                titles.append(i.cards[j].card_title + f"_{j+1}\n")

        y = [j.is_complete for j in i.cards]
        plt.ylim([0, 100])
        plt.bar(titles, y)

        if titles == []:
            continue
        plt.savefig(f"kanban_app\static\graphs\list_{i.list_id}")


    t_date = datetime.today()
    return render_template("summary.html", user=current_user, logged_in=current_user.is_authenticated, user_lists=user_lists,t_date=t_date )

kanban_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Kanban application</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat|Sacramento" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css')}}">


  {% block styles %}
  {% endblock %}
</head>

<body>
  {% block navbar_sect %}

  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand brand-font" href="#">&nbsp;Kanban</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ">
          
          <li class="nav-item ">
            <a class="nav-link nav21" href="{{ url_for('views.home') }}">Home</a>
          </li>
          
          {% if not logged_in: %}
          <li class="nav-item ">
            <a class="nav-link nav21" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link nav21" href="{{ url_for('auth.register') }}">Register</a>
          </li>
        {% endif %}

        {% if logged_in: %}
        <li class="nav-item ">
          <a class="nav-link nav21" href="{{ url_for('views.summary') }}">Summary</a>
        </li>

        <li class="nav-item ">
          <a class="nav-link nav21" href="{{ url_for('auth.logout') }}">Log Out</a>
        </li>
        {% endif %}
        <li>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </li>

        </ul>
        
      </div>
    </div>
  </nav>

 
  {% endblock %}
  {% block content %}

  {% endblock %}

</body>

</html>

kanban_app/templates/board.html
{% extends "base.html" %}

{% block content %}

<br>
<h6 class="card-text user-name mar-fix" style="display: inline-block; font-size: x-large; padding-left: 0px;">
    Hi,
    {% for j in range(88) %}
        &nbsp;
    {% endfor %}
</h6>
<a class="nav-link btn  btn-block btn-large" style="display: inline-block ; padding: 2.5px; font-size: large;" href="{{ url_for('views.createList')}}">+Add List</a>



{% if user_lists|length == 0 %}
<h4 class="card-text"> Board is Empty! Add New todo list</h4>
<ul class="nav-item">

</ul>
{% else %}


<div class="row">

    {% for i in range(user_lists|length) %}

    <div class="list-column col-lg-3 col-md-4">
        <div class="card card-list">
            <div class="card-header ">

                <div class="dropdown">
                    <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">
                        {{ user_lists[i].list_name }}
                    </button>
                    <ul class="dropdown-menu button-color">
                        <li><a class="dropdown-item btn btn-primary button-color"
                                href="{{ url_for('views.updateList', id = user_lists[i].list_id) }}">Update</a>
                        </li>
                        <li><a class="dropdown-item btn btn-outline-danger button-color"
                                href="{{ url_for('views.deleteList', id = user_lists[i].list_id) }}"
                                onclick="return confirm('Are you sure to delete?')">Delete</a>
                        </li>
                    </ul>
                </div>

            </div>
            <div class="card-body card-body-color overflow-auto card-list-body">

                <p class="card-text">{{ user_lists[i].description }}</p>
                <a class="nav-link btn btn-outline-light" role="button" style="display: inline-block ; padding: 3px;" href="{{ url_for('views.createCard', li_id = user_lists[i].list_id) }}">+Add
                    Task</a>

                {% if user_cards|length == 0 %}

                <h6 class="card-text"> List is Empty! Add New new remainder</h6>

                {% else %}

                {% for j in user_cards[i] %}
                <div class="list-column col-lg-12">
                    <div class="card card-card1">
                        <div class="card-header">
                            <div class="dropdown">
                                <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">
                                    {{ j.card_title }}
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item btn btn-outline-primary"
                                            href="{{ url_for('views.updateCard', c_id = j.card_id) }}">Update</a>
                                    </li>
                                    <li><a class="dropdown-item btn btn-outline-danger"
                                            href="{{ url_for('views.deleteCard', c_id = j.card_id) }}"
                                            onclick="return confirm('Are you sure to delete?')">Delete</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ j.content }}</p>
                            <h6 class="card-text">{{ j.deadline.strftime('%d-%m-%Y') }}</h6>

                            <div class="progress">
                                <div {% if j.is_complete==100 %} class="progress-bar bg-success" {% else %}
                                    class="progress-bar" {% endif %} role="progressbar"
                                    style="width: {{j.is_complete}}%;" aria-valuenow="{{j.is_complete}}"
                                    aria-valuemin="0" aria-valuemax="100"></div>
                            </div>


                        </div>
                    </div>
                </div>

                {% endfor %}

                {% endif %}


            </div>

        </div>
    </div>

    {% endfor %}

</div>
{% endif %}

{% endblock %}

kanban_app/templates/editCard.html
{% extends "base.html" %}

{% block content %}

<div class="box card-div">
    <h1>Update a Task</h1>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}



    <form action="{{ url_for('views.updateCard', c_id = c_id)}}" method="post">

        <div class="form-group">
            <label for="list-card">Lists</label>
            <select name="list-card" class="custom-select custom-dropdown custom-form-input">

                {% for i in user.lists %}
                {% if i.list_id == li_id %}
                <option value="{{ i.list_id }}" selected>{{ i.list_name }}</option>
                {% else %}
                <option value="{{ i.list_id }}">{{ i.list_name }}</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="name">Title </label>
            <input type="text" name="name" placeholder="title" value='{{c.card_title}}' required="required" />
        </div>

        <div>
            <label for="content">Content </label>
            <input type="text" name="content" placeholder="Content" value='{{c.content}}' required="required" />
        </div>

        <div>
            <label for="deadline">Deadline </label>
            <input type="date" name="deadline" placeholder="Description" value='{{c.deadline.strftime("%Y-%m-%d")}}'
               min="{{ t_date }}" required="required" />
        </div>

        <p>Task Progress</p>
        
        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="0"
        {% if c.is_complete == 0 %} checked {% endif %}>
        <label class="form-check-label " for="card_radio">
            0%
        </label>

        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="25"
        {% if c.is_complete == 25 %} checked {% endif %}>
        <label class="form-check-label" for="card_radio">
            25%
        </label>

        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="50"
        {% if c.is_complete == 50 %} checked {% endif %}>
        <label class="form-check-label" for="card_radio">
            50%
        </label>

        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="75"
        {% if c.is_complete == 75 %} checked {% endif %}>
        <label class="form-check-label" for="card_radio">
            75%
        </label>
        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="100"
        {% if c.is_complete == 100 %} checked {% endif %}>
        <label class="form-check-label" for="card_radio">
            100%
        </label>

        <button type="submit" class="btn btn-primary btn-block btn-large">Submit</button>
    </form>

</div>

{% endblock %}

kanban_app/templates/editList.html
{% extends "base.html" %}

{% block content %}

<div class="box card-div">
    <h1>Update a List</h1>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <form action="{{ url_for('views.updateList', id = curr_id)}}" method="post">

        <div>
            <label for="name">Name  </label>
            <input type="text" name="name" placeholder="name" value="{{ curr_list.list_name }}" required="required" />
        </div>
        
        <div>
            <label for="description">Description    </label>
            <input type="text" name="description" placeholder="Description" value="{{ curr_list.description }}" required="required" />
        </div>

        <button type="submit" class="btn btn-primary btn-block btn-large">Submit</button>
    </form>

</div>

{% endblock %}

kanban_app/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="box main-box">
    <h1 class="main">Kanban Application</h1>
    {% if not logged_in: %}
    <a href="{{ url_for('auth.login') }}" class="btn btn-primary btn-block btn-large main-tag">Login</a>
    <a href="{{ url_for('auth.register') }}" class="btn btn-secondary btn-block btn-large main-tag">Register</a>
    {% endif %}
</div>

{% endblock %}

kanban_app/templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="box">
    <h1>Login</h1>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <form action="{{ url_for('auth.login') }}" method="post">
        <input type="text" name="email" placeholder="Email" required="required"/>
        <input type="password" name="password" placeholder="Password" required="required"/>
        <button type="submit" class="btn btn-primary btn-block btn-large">Let me in.</button>
    </form>
    
</div>

{% endblock %}

kanban_app/templates/newCard.html
{% extends "base.html" %}



{% block styles %}
<style>

</style>
{% endblock %}

{% block content %}

<div class="box card-div">
    <h1>Add a Task</h1>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}



    <form action="{{ url_for('views.createCard', li_id = li_id)}}" method="post">

        <div class="form-group">
            <label for="list-card">Lists</label>
            <select name="list-card" class="custom-select custom-dropdown custom-form-input">

                {% for i in user.lists %}
                {% if i.list_id == li_id %}
                <option value="{{ i.list_id }}" selected>{{ i.list_name}}</option>
                {% else %}
                <option value="{{ i.list_id }}">{{ i.list_name}}</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="name">Title </label>
            <input type="text" name="name" placeholder="title" required="required" />
        </div>

        <div>
            <label for="content">Content </label>
            <input type="text" name="content" placeholder="Content" required="required" />
        </div>

        <div>
            <label for="deadline">Deadline </label>
            <input type="date" min="{{ t_date }}" name="deadline" placeholder="Description" required="required" />
        </div>

        <p>Task Progress</p>
        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="0"
            checked>
        <label class="form-check-label " for="card_radio">
            0%
        </label>

        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="25">
        <label class="form-check-label" for="card_radio">
            25%
        </label>
        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="50">
        <label class="form-check-label" for="card_radio">
            50%
        </label>
        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="75">
        <label class="form-check-label" for="card_radio">
            75%
        </label>
        <input class="form-check-input radio-inline" type="radio" name="completed_percent" id="card_radio" value="100">
        <label class="form-check-label" for="card_radio">
            100%
        </label>
        <!-- </div> -->




        <button type="submit" class="btn btn-primary btn-block btn-large">Submit</button>
    </form>

</div>

{% endblock %}

kanban_app/templates/newList.html
{% extends "base.html" %}

{% block content %}

<div class="box card-div">
    <h1>Add a Todo List</h1>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <form action="{{ url_for('views.createList') }}" method="post">

        <div>
            <label for="name">Name  </label>
            <input type="text" name="name" placeholder="name" required="required" />
        </div>

        <div>
            <label for="description">Description    </label>
            <input type="text" name="description" placeholder="Description" required="required" />
        </div>
        <button type="submit" class="btn btn-primary btn-block btn-large">Submit</button>
    </form>

</div>

{% endblock %}

kanban_app/templates/register.html
{% extends "base.html" %}

{% block content %}

<div class="box">
	<h1>Register</h1>
    <form action="{{ url_for('auth.register') }}" method="post">
    	<input type="text" name="name" placeholder="Name" required="required" />
		<input type="email" name="email" placeholder="Email" required="required" />
        <input type="password" name="password" placeholder="Password" required="required" />
        <button type="submit" class="btn btn-primary btn-block btn-large">Sign me up.</button>
    </form>
</div>

{% endblock %}

kanban_app/templates/summary.html
{% extends "base.html" %}

{% block content %}
<br>

<h6 class="card-text user-name mar-fix" style="font-size: x-large;">
    Hi {{ user.name | capitalize }},

</h6>

{% if user_lists|length == 0 %}
<h4 class="card-text"> Board is Empty! Add New todo list</h4>

{% else %}


<div class="row">

    {% for i in range(user_lists|length) %}

    <div class="list-column col-lg-3 col-md-6">
        <div class="card h-100 card-list">
            <div class="card-header">
                <h5 class="card-text style" style="padding: 5px;">{{user_lists[i].list_name}}</h5>
            </div>
            <div class="card-body card-list-body overflow-auto">
                {% if user_lists[i].cards | length == 0 %}

                <h5 style="width: 100px;
                margin-left: auto;
                margin-right: auto;">No Tasks yet!</h5>

                {% else %}
                {% set path = 'list_'+ user_lists[i].list_id | string() +".png" %}
                <div class="text-center">
                    <img src='..\static\graphs\{{path}}' alt="{{user_lists[i].list_name}}" class="img-fluid mh-100">
                </div>
                <h6>Tasks Remaining - {{ user_lists[i].tasks_remaining}}</h6>
                <h6>Tasks Completed - {{ user_lists[i].tasks_completed}}</h6>
                
                {% for j in range(user_lists[i].cards|length) %}
                    {% if user_lists[i].cards[j].deadline < t_date %}
                        
                        {% if j==0 %}
                            <h6><b>Deadline passed tasks:</b></h6>
                        {% endif %}

                        <h6>{{user_lists[i].cards[j].card_title}}</h6>
                      
                    {% endif %}
                {% endfor %}
                {% endif %}
            
            </div>

        </div>
    </div>


    {% endfor %}
</div>
{% endif %}

{% endblock %}